imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                #result_cache_driver:
                #    type: memcached
                #    host: %memcached_server%
                #    port: 11211
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                dql:
                    datetime_functions:
                        DATE: Disko\CoreBundle\Query\Mysql\Date
                        DATEADD: Disko\CoreBundle\Query\Mysql\DateAdd
                        DATEDIFF: Disko\CoreBundle\Query\Mysql\DateDiff
                        DATE_FORMAT: Disko\CoreBundle\Query\Mysql\DateFormat
                        DAY: Disko\CoreBundle\Query\Mysql\Day
                        DAYNAME: Disko\CoreBundle\Query\Mysql\DayName
                        STRTODATE: Disko\CoreBundle\Query\Mysql\StrToDate
                        TIMESTAMPDIFF: Disko\CoreBundle\Query\Mysql\TimestampDiff
                        WEEK: Disko\CoreBundle\Query\Mysql\Week
                        YEAR: Disko\CoreBundle\Query\Mysql\Year

                    numeric_functions:
                        ACOS: Disko\CoreBundle\Query\Mysql\Acos
                        ASIN: Disko\CoreBundle\Query\Mysql\Asin
                        ATAN2: Disko\CoreBundle\Query\Mysql\Atan2
                        ATAN: Disko\CoreBundle\Query\Mysql\Atan
                        COS: Disko\CoreBundle\Query\Mysql\Cos
                        COT: Disko\CoreBundle\Query\Mysql\Cot
                        ROUND: Disko\CoreBundle\Query\Mysql\Round
                        SIN: Disko\CoreBundle\Query\Mysql\Sin
                        TAN: Disko\CoreBundle\Query\Mysql\Tan
                        RAND: Disko\CoreBundle\Query\Mysql\Rand

                    string_functions:
                        CHARLENGTH: Disko\CoreBundle\Query\Mysql\CharLength
                        CONCAT_WS: Disko\CoreBundle\Query\Mysql\ConcatWs
                        COUNTIF: Disko\CoreBundle\Query\Mysql\CountIf
                        DEGREES: Disko\CoreBundle\Query\Mysql\Degrees
                        FIELD: Disko\CoreBundle\Query\Mysql\Field
                        FINDINSET: Disko\CoreBundle\Query\Mysql\FindInSet
                        GROUPCONCAT: Disko\CoreBundle\Query\Mysql\GroupConcat
                        IFELSE: Disko\CoreBundle\Query\Mysql\IfElse
                        IFNULL: Disko\CoreBundle\Query\Mysql\IfNull
                        MATCHAGAINST: Disko\CoreBundle\Query\Mysql\MatchAgainst
                        MD5: Disko\CoreBundle\Query\Mysql\Md5
                        MONTH: Disko\CoreBundle\Query\Mysql\Month
                        MONTHNAME: Disko\CoreBundle\Query\Mysql\MonthName
                        NULLIF: Disko\CoreBundle\Query\Mysql\NullIf
                        RADIANS: Disko\CoreBundle\Query\Mysql\Radians
                        SHA1: Disko\CoreBundle\Query\Mysql\Sha1
                        SHA2: Disko\CoreBundle\Query\Mysql\Sha2

stof_doctrine_extensions:
    default_locale: en
    orm:
        default:
            tree: true
            timestampable: true
            translatable: true
            loggable: true
            sluggable: true
            sortable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Disko\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        confirmation:
            enabled:    true
        form:
            type: my_user_registration
    from_email:
        address:        xxx@xxx.com
        sender_name:    xxx xxx

# Paginator
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: AdminBundle:partials:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

# Breadcrumb
white_october_breadcrumbs:
    separator: ''
    separatorClass: 'divider'

# Maintenance bundle
lexik_maintenance:
    authorized:
        ips: ['127.0.0.1']                                                  # Optional. Authorized ip addresses
        query: { }                                                          # Optional. Authorized request query parameter (GET/POST)
        route:                                                              # Optional. Authorized route name
        attributes:                                                         # Optional. Authorized route attributes
    driver:
        ttl:    50000
         # File driver
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'                # class for file driver
        options: {file_path: %kernel.root_dir%/cache/lock}                         # file_path is the complete path for create the file


liip_imagine:
    # At un comment for AWSS3
    # cache: resolver_local
    # data_loader: import
    resolvers:
        default:
          web_path: ~

        resolver_as3:
            aws_s3:
                client_config:
                  key:    %amazon_s3.key%
                  secret: %amazon_s3.secret%
                  region: %amazon_s3.region%
                bucket:     %amazon_s3.bucket.cache%
                get_options:
                  Scheme: 'https'
                put_options:
                  CacheControl: 'max-age=100'

    filter_sets:
        keyword:
            quality: 100
            filters:
                thumbnail: { size: [188, 188], mode: outbound }


knp_gaufrette:
    adapters:
        local:
            local:
                directory: uploads/
                create: true
        aws:
            aws_s3:
                service_id: 'aws_s3.client'
                bucket_name: %amazon_s3.bucket%
                options:
                    create: true
                    directory: 'uploads'
    filesystems:
        current:
            adapter:    local
            alias:      current