_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

example:
    resource: "@ExampleBundle/Resources/config/routing.yml"
    prefix:   /