# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    aws.gaufrette.listener.postLoad:
        class: Disko\CoreBundle\Listener\GaufretteListener
        calls:
            - [setFileSystem, ['@knp_gaufrette.filesystem_map']]
        tags:
            - { name: doctrine.event_listener, event: postLoad, method: postLoad, priority: 100  }
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate, priority: 100  }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist, priority: 100  }
            - { name: doctrine.event_listener, event: preRemove, method: preRemove, priority: 100  }

imports:
    - { resource: services/aws.yml }
