services:
    fos_user.doctrine_registry:
        alias: doctrine
    aws_s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                key:    %amazon_s3.key%
                secret: %amazon_s3.secret%
                region: %amazon_s3.region%

    liip_imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@aws_s3.client"
            - %amazon_s3.bucket.cache%
        tags:
            - {name: 'liip_imagine.cache.resolver', resolver: 'resolver_as3'}

    liip_imagine.binary.loader.stream.import:
        class: Liip\ImagineBundle\Binary\Loader\StreamLoader
        arguments:
            - 'https://%amazon_s3.bucket%.s3-%amazon_s3.region%.amazonaws.com/uploads/'
        tags:
            - { name: 'liip_imagine.binary.loader', loader: 'import' }